spring.datasource.url=jdbc:postgresql://localhost:5432/distributed_cache
spring.datasource.username=sripotda
spring.datasource.driver-class-name=org.postgresql.Driver
cache.nodes=http://localhost:8081,http://localhost:8082,http://localhost:8083